apiVersion: v1
kind: Service
metadata:
  name: flaskapp-capstone
  labels:
    app: flaskapp-capstone
spec:
  ports:
  - name: "8000"
    port: 8000 # port of the serivce
    targetPort: 80 # port of the container that service will forward to 
    protocol: TCP
  selector:
    app: flaskapp-capstone
    version: v2
  type: LoadBalancer