apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myCluster
  region: us-east-1

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    amiFamily: AmazonLinux2
    # desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: capstone-keypair